[scene.treasure-vault]
name = "vault"
background = "vault.jpg"

[scene.home]
name = "home"
background = "home.jpg"

[scene.secret2]
name = "secret2"
background = "secret2.jpg"

[character.explorer]
name = "explorer"
avatar = "player_happy.png"

[event.start]
scene = "vault"
dialogue = "to_vault"

[dialogue.to_vault]
character = "explorer"
text = "我用鑰匙打開了地下寶庫的大門，裡面有寶石和金幣。"
options = [
  { text = "收集寶藏", next = "treasure" }
]

[dialogue.treasure]
character = "explorer"
text = "我收集了一些寶藏，準備帶回家。"
options = [
  { text = "繼續探索", next = "explore" },
  { text = "直接離開", next = "leave" }
]
