[scene.library]
name = "library"
background = "library.jpg"

[scene.secret-garden]
name = "Secret Garden"
background = "garden.jpg"

[character.explorer]
name = "Explorer"
avatar = "player_happy.png"
tachie = "player_happy.png"

[character.iris]
name = "Guardian Iris"
avatar = "iris.png"
tachie = "iris.png"

[character.lena]
name = "Guardian Lena"
avatar = "girl.png"
tachie = "girl.png"

[item.ancient-key]
name = "Ancient Key"
description = "The key to unlocking the underground treasure house"
icon = "key.png"

[item.decryption-book]
name = "Decryption Book"
description = "Contains clues to unlock the secret"
icon = "book.png"

[event.start]
scene = "library"
dialogue = "initial_meeting"

[dialogue.initial_meeting]
character = "explorer"
text = "This is the legendary ancient library! I heard that the secret to the treasure is hidden here. I must solve the puzzle and take the treasure home! Huh? There is a person there, could it be the legendary pig? Curator Iris?"
options = [
 { text = "Look for Iris and ask for information about the treasure.", next = "iris_intro" },
 { text = "Explore around the library.", next = "explore_library" }
]

[dialogue.iris_intro]
character = "iris"
text = "You look like someone who is here to look for treasure. The road to the treasure is full of dangers, and many people return without success. Even so, are you still willing to go?"
options = [
 { text = "Of course! I'm ready, please tell me more.", next = "iris_help" },
 { text = "I just came to take a look.", next = "explore_library" }
]

[dialogue.iris_help]
character = "iris"
text = "Well, if you're really ready, you need to find the ancient decryption book first. It's hidden somewhere in the library."
options = [
 { text = "Looking for the decrypted book.", next = "find_book" },
 { text = "Leave the library.", next = "leave_library" }
]

[dialogue.find_book]
character = "explorer"
text = "There is an ancient book here that looks very mysterious! It is hidden deep in the library. It must be the decryption book I am looking for."
options = [
 { text = "Pick up the decryption book.", inventory_add = "decryption-book", next = "return_to_iris" }
]

[dialogue.return_to_iris]
character = "explorer"
text = "Now go find Iris!"
options = [
 { text = "Show the decrypted book to Iris.", next = "show_book_to_iris" }
]

[dialogue.show_book_to_iris]
character = "iris"
text = "This is the book! Now you can travel to the Secret Garden and find the ancient key."
options = [
 { text = "Pick up the decryption book and head to the Secret Garden.", inventory_add = "decryption-book", event = "change_scene_to_garden" },
 { text = "Don't go there yet.", next = "stay_in_library" }
]

[dialogue.stay_in_library]
character = "explorer"
text = "I decided to explore the library for a while, maybe I'll find other useful clues."
options = [
 { text = "Continue exploring the library.", next = "explore_library_more" },
 { text = "Now head to the Secret Garden.", event = "change_scene_to_garden" }
]

[dialogue.explore_library_more]
character = "explorer"
text = "Every corner of the library is full of mysteries, but now it seems there are no more clues."
options = [
 { text = "Head to the Secret Garden.", event = "change_scene_to_garden" }
]

[event.change_scene_to_garden]
scene = "secret-garden"
dialogue = "garden_arrival"

[dialogue.garden_arrival]
character = "explorer"
text = "The Secret Garden is an enchanting place filled with exotic flowers and maze-like paths."
options = [
 { text = "Search for the ancient key.", next = "find_key" },
 { text = "Explore the gardens.", next = "explore_garden" }
]

[dialogue.find_key]
character = "explorer"
text = "Behind a hidden fountain, I found the ancient key."
options = [
 { text = "Pick up the key.", inventory_add = "ancient-key", event = "change_scene_to_vault" }
]

[dialogue.explore_garden]
character = "explorer"
text = "Every corner in the garden is full of mystery. Suddenly, a guardian named Lena appears."
options = [
 { text = "Talk to Lena.", next = "lena_intro" },
 { text = "Continue exploring the garden.", next = "explore_garden_more" }
]

[dialogue.lena_intro]
character = "lena"
text = "Hello, explorer. What are you looking for here?"
options = [
 { text = "Tell Lena about the treasure.", next = "lena_help" },
 { text = "Hide your purpose.", next = "lena_suspect" }
]

[dialogue.lena_help]
character = "lena"
text = "I know what you are looking for. This ancient key will help you."
options = [
 { text = "Thank Lena and head to the underground treasure trove", inventory_add = "ancient-key", event = "change_scene_to_vault" },
 { text = "Leave the garden.", next = "leave_garden" }
]
