[scene.library]
name = "library"
background = "library.jpg"

[scene.secret-garden]
name = "secret-garden"
background = "garden.jpg"

[scene.treasure-vault]
name = "vault"
background = "vault.jpg"

[character.explorer]
name = "explorer"
avatar = "player_happy.png"
tachie = "player_terrified.png"

[character.iris]
name = "iris"
avatar = "iris.png"
tachie = "iris.png"

[character.lena]
name = "lena"
avatar = "girl.png"
tachie = "girl.png"

[item.ancientkey]
name = "ancientkey"
description = "鑰匙：可以開啟地下寶庫"
icon = "key.png"

[item.decryptionbook]
name = "decryptionbook"
description = "解密書：含有解開秘密的線索"
icon = "book.png"

[dialogue.initial_meeting]
character = "explorer"
text = "這裡就是傳說中的圖書館! 聽說這隱藏著通往寶藏所在處的秘密，我一定要解開謎題帶著寶物回家!"
background = "library.jpg"
options = [
  { text = "咦? 那裏有個人", next = "find_iris", affinity_change = 0 },
  { text = "在圖書館四處探索", next = "explore_library", affinity_change = -20 }
]


[dialogue.find_iris]
character = "explorer"
background = "library.jpg"
text = "難道就是傳說中的館長艾瑞斯嗎?"
options = [
  { text = "尋找艾瑞斯並詢問關於寶藏的信息", next = "iris_intro", affinity_change = 10 },
  { text = "在圖書館四處探索", next = "explore_library", affinity_change = -10 }
]

[dialogue.explore_library]
character = "explorer"
background = "library.jpg"
text = "這裡看起來被整理得很好，想必一定是館長很可靠吧！"
options = [
  { text = "回頭去找艾瑞斯問問看吧", next = "iris_help", affinity_change = 10 },
  { text = "我還是比較相信我自己！", next = "explore_library_more", affinity_change = 20 }
]

[dialogue.iris_intro]
character = "iris"
background = "library.jpg"
text = "你一看就是來尋找寶藏的人，通往寶藏之路充滿險境，許多人都無功而返，即便如此你還是願意前往嗎?"
options = [
  { text = "當然!我準備好了，請告訴我更多訊息", next = "iris_help", affinity_change = 10 },
  { text = "我只是來看看", next = "explore_library", affinity_change = 0 }
]

[dialogue.iris_help]
character = "iris"
background = "library.jpg"
text = "好吧，如果你真的準備好了，你需要先找到古老的解密書它藏在圖書館的某處"
options = [
  { text = "尋找解密書", next = "find_book", affinity_change = -20 },
  { text = "請你直接告訴我答案吧", next = "iris_re_help", affinity_change = -20 }
]

[dialogue.iris_re_help]
character = "iris"
background = "library.jpg"
text = "請出去"
options = [
  { text = "好吧我找就是了", next = "find_book", affinity_change = -10 }
]


[dialogue.find_book]
character = "explorer"
background = "library.jpg"
text = "這裡有一本看起來分常神秘的古書籍!又藏在圖書館深處，想必它正是我要找的解密書"
options = [
  { text = "拿起解密書！", next = "return_to_iris", affinity_change = 20 }
]

[dialogue.return_to_iris]
character = "explorer"
background = "library.jpg"
text = "現在去找艾瑞斯吧!"
options = [
  { text = "向艾瑞斯展示解密書", inventory_add = "decryptionbook", next = "show_book_to_iris", affinity_change = 0 }
]

[dialogue.show_book_to_iris]
character = "iris"
background = "library.jpg"
text = "這就是那本書！現在，你可以前往秘密花園，找到古老的鑰匙"
options = [
  { text = "拿起解密書並前往秘密花園", next = "garden_arrival", affinity_change = 10 },
  { text = "先不前往", next = "stay_in_library", affinity_change = 0 }
]

[dialogue.stay_in_library]
character = "explorer"
background = "library.jpg"
text = "我決定先在圖書館再探索一會兒，也許還會發現其他有用的線索"
options = [
  { text = "繼續探索圖書館", next = "explore_library_more", affinity_change = 0 },
  { text = "現在前往秘密花園", next = "garden_arrival", affinity_change = 10 }
]

[dialogue.explore_library_more]
character = "explorer"
background = "library.jpg"
text = "圖書館裡的每一個角落都充滿了神秘，但現在似乎沒有更多的線索了"
options = [
  { text = "前往秘密花園", next = "garden_arrival", affinity_change = 10 }
]

[dialogue.garden_arrival]
character = "explorer"
background = "garden.jpg"
text = "秘密花園是個迷人的地方，充滿了奇異的花草和迷宮般的小徑"
options = [
  { text = "探索花園", next = "explore_garden", affinity_change = 10 },
  { text = "尋找古老的鑰匙", next = "explore_garden", affinity_change = 20 }
]

[dialogue.explore_garden]
character = "explorer"
background = "garden.jpg"
text = "花園裡的每一個轉角都充滿了神秘。突然，一位名叫萊娜的守護者出現了"
options = [
  { text = "與萊娜交談", next = "lena_intro", affinity_change = 40 },
  { text = "繼續探索花園", next = "explore_garden_more", affinity_change = -20 }
]

[dialogue.lena_intro]
character = "lena"
background = "garden.jpg"
text = "你好，我是萊娜。探險家你在這裡尋找什麼？"
options = [
  { text = "告訴萊娜關於寶藏的事", next = "lena_help", affinity_change = 0 },
  { text = "隱瞞你的目的", next = "lena_suspect", affinity_change = -20 }
]

[dialogue.lena_help]
character = "lena"
background = "garden.jpg"
text = "我知道你在尋找什麼。這把古老的鑰匙將會幫助你"
options = [
  { text = "感謝萊娜並前往地下寶庫", inventory_add = "ancientkey", next = "to_vault", affinity_change = 10 },
  { text = "離開花園", next = "leave_garden", affinity_change = 0 }
]

[dialogue.lena_suspect]
character = "lena"
background = "garden.jpg"
text = "隱瞞目的會引起萊娜的懷疑，她可能不願意幫助你。"
options = [
  { text = "告訴她真相", next = "lena_help", affinity_change = 10 },
  { text = "繼續隱瞞，我還是想靠自己", next = "find_key", affinity_change = -20 }
]


[dialogue.find_key]
character = "explorer"
background = "garden.jpg"
text = "在一個隱蔽的噴泉後面，我找到了古老的鑰匙!"
options = [
  { text = "拿起鑰匙", inventory_add = "ancientkey", next = "to_vault", affinity_change = 0 }
]


[dialogue.explore_garden_more]
character = "explorer"
background = "garden.jpg"
text = "你繼續在花園裡探索，但似乎沒有更多的線索了。"
options = [
  { text = "返回去尋求幫助", next = "lena_help", affinity_change = -10 }
]
